platform :ios, '7.0'

pod 'LRResty', '~> 0.11'
pod 'TouchJSON', '~> 1.1'
pod 'FlatUIKit', '~> 1.3'
pod 'TPKeyboardAvoiding', '~> 1.2'
pod 'MBProgressHUD','~> 0.8'
pod 'SpinKit', '~> 1.0.1'
pod 'DateTools'
pod 'TSMiniWebBrowser', '~> 1.0'